export const makeTurn = (payload) => ({type: 'makeTurn', payload})
export const switchTurn = () => ({type: 'switchTurn'})
export const checkWinner = () => ({type: 'checkWinner'})
export const openModal = () => ({type: 'openModal'})
export const setRoomName = (payload) => ({type: 'setRoomName', payload})
export const setUserName = (payload) => ({type: 'setUserName', payload})
export const exitRoom = () => ({type:'exitRoom'})
export const getUrlParams = (payload) => ({type: 'getUrlParams', payload})
export const addUser = (payload) => ({type: 'addUser', payload})
export const setSocket = (payload) => ({type: 'setSocket', payload})
export const setSymbol = (payload) => ({type: 'setSymbol', payload})
export const setField = (payload) => ({type: 'setField', payload})
export const setTurn = (payload) => ({type: 'setTurn', payload})